### ISSUE TITLE
Experience with the code for communicating with Pylontech batteries 

### ISSUE THREAD

**Issue by alpujarra** [AlexanderPollak/Solar-Control-Program#1]
Hi Alexander, in my solar installation I have Pylontech US2000 Plus batteries and I would like to do exactly what you have already done, that is,  obtaining the SoC directly from the batteries instead through the Axpert inverter estimation. Looking about this and how to do it I have found your repo. I see that you update the repo last time one year ago and that there are no other contributors. I would like to ask you if you finally use this code in your installation and if you really tested with real Pylontech batteries. In summary, I would really appreciate if you could please share with me your experience with this code and your opinion about the feasibility to use it in my installation.

Thank you very much for your help. 

Best regards 

Francisco

**Comment by AlexanderPollak** [comment]
Hi Francisco,

I currently only use part of the code to get the SoC. 
The batteries are connected to a Raspberry PI via the RS232 connection, and then I use one script to initialize the connection, which tells the battery to change the bitrate.
And then I have another script that periodically queries the SoC. Ideally if I have more time, I would use it to the my Inverter when to switch off and on.
But at the moment I do that vie that battery voltage.

If you keen on contributing to that, that would be great. The communication methods are pretty much all in existence. 

Best,

Alexander

**Comment by AlexanderPollak** [comment]
Hi Francisco,

I finally had some time to sort out the code and I am running it at the moment.
The code reads the SoC of the 6 Pylontech modules and enables and disables the "Load Shave"
function of the XW+ inverter, depending on the specified SoC. 
Currently in winter operation mode, it enables the inverter at 90% SoC and disables it at 50% SoC, so
that in case of a grid failure I still have 50% SoC as a backup to keep everything running for a couple of days.
